services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    hostname: adguard.antoine.com
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APP_DATA}/adguardhome/config:/opt/adguardhome/conf
      - ${DOCKER_APP_DATA}/adguardhome/work:/opt/adguardhome/work
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguardhome.rule=Host(`adguardhome.palomabeach.ovh`)
      - traefik.http.routers.adguardhome.entrypoints=websecure
      - traefik.http.routers.adguardhome.tls=true
      - traefik.http.routers.adguardhome.service=adguardhome
      - traefik.http.services.adguardhome.loadbalancer.server.port=80
    ports:
      - 53:53 # DNS
        #- 443:443/tcp # HTTPS/DNS-over-HTTPS
        #- 853:853/tcp # DNS-over-TLS
        #- 784:784/udp # DNS-over-QUIC
    networks:
      mac_vlan:
        aliases:
        - adguardhome
        ipv4_address: 192.168.1.253
      traefik_proxy:
        aliases:
        - adguardhome
        ipv4_address: 172.10.0.4
