services:
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr.palomabeach.ovh
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.palomabeach.ovh`)
      - traefik.http.routers.flaresolverr.entrypoints=websecure
      - traefik.http.routers.flaresolverr.tls=true
      - traefik.http.routers.flaresolverr.service=flaresolverr
      - traefik.http.services.flaresolverr.loadbalancer.server.port=8191
    networks:
      traefik_proxy:
        aliases:
         - flaresolverr
        ipv4_address: 172.10.0.25
