services:
  docker-gc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - CRON="0 0 * * *"
      - FORCE_IMAGE_REMOVAL=1
      - FORCE_CONTAINER_REMOVAL=0
      - GRACE_PERIOD_SECONDS=604800
      - DRY_RUN=0
      - CLEAN_UP_VOLUMES=1
      - TZ=${TZ}
      - DOCKER_HOST=${DOCKER_HOST}
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_APP_DATA}/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
    networks:
      socket_proxy:
        aliases:
          - docker-gc
        ipv4_address: 172.30.0.2 
