services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    restart: unless-stopped
    group_add:
      - "105"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APP_DATA}/jellyfin/config:/config
      - ${NAS}/medias:/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.palomabeach.ovh`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.docker.network=proxy
    networks:
      traefik_proxy:
        aliases:
        - jellyfin
        ipv4_address: 172.10.0.10
