services:
  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE_NEXTCLOUD}
      - MYSQL_USER=${MYSQL_USER_NEXTCLOUD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_NEXTCLOUD}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - REDIS_HOST=redis
    ports:
      - 127.0.0.1:9001:9000
    volumes:
      - ${DOCKER_APP_DATA}/nextcloud:/var/www/html
    networks:
      database_proxy:
        aliases:
        - nextcloud
        ipv4_address: 172.50.0.10

  nginx-nextcloud:
    image: nginx:alpine
    container_name: nginx-nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud
    volumes:
      - ${DOCKER_APP_DATA}/nginx-nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.palomabeach.ovh`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
    networks:
      database_proxy:
        aliases:
        - nginx-nextcloud
        ipv4_address: 172.50.0.11
      traefik_proxy:
        aliases:
        - nginx-nextcloud
        ipv4_address: 172.10.0.28
