services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    hostname: plex.palomabeach.ovh
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APP_DATA}/plex/library:/config
      - ${NAS}/medias:/medias
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.palomabeach.ovh`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.service=plex
      - traefik.http.services.plex.loadbalancer.server.port=32400
    networks:
      traefik_proxy:
        aliases:
        - plex
        ipv4_address: 172.10.0.12
