services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    hostname: radarr.palomabeach.ovh
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_APP_DATA}/radarr/config:/config
      - ${NAS}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.palomabeach.ovh`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    networks:
      traefik_proxy:
        aliases:
          - radarr
        ipv4_address: 172.10.0.22
