services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr.palomabeach.ovh
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_APP_DATA}/sonarr/config:/config
      - ${NAS}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.palomabeach.ovh`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    networks:
      traefik_proxy:
        aliases:
          - sonarr
        ipv4_address: 172.10.0.21
