services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    hostname: tautulli.palomabeach.ovh
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APP_DATA}/tautulli/config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.palomabeach.ovh`)
      - traefik.http.routers.tautulli.entrypoints=websecure
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.service=tautulli
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
    networks:
      traefik_proxy:
        aliases:
        - tautulli
        ipv4_address: 172.10.0.14
